// Mocks generated by Mockito 5.0.2 from annotations
// in financial_systems_coursework/test/repository/StockDataProvider_test.dart.
// Do not manually edit this file.

import 'package:financial_systems_coursework/repository/DBManager.dart' as _i3;
import 'package:financial_systems_coursework/repository/StockDataCollector.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: comment_references
// ignore_for_file: unnecessary_parenthesis

/// A class which mocks [StockDataCollector].
///
/// See the documentation for Mockito's code generation for more information.
class MockStockDataCollector extends _i1.Mock
    implements _i2.StockDataCollector {
  MockStockDataCollector() {
    _i1.throwOnMissingStub(this);
  }
}

/// A class which mocks [DBManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockDBManager extends _i1.Mock implements _i3.DBManager {
  MockDBManager() {
    _i1.throwOnMissingStub(this);
  }
}
